# Generated by Django 3.2 on 2021-05-20 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 20, 23, 23, 6, 818504)),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_launch_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 20, 23, 23, 6, 817493)),
        ),
    ]
