# Generated by Django 3.2 on 2021-05-24 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20210524_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
        migrations.AddField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 24, 22, 56, 31, 328512)),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_launch_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 24, 22, 56, 31, 328512)),
        ),
    ]
